New guidelines for developpers
CoBrALab/RABIES pull request #319
Opened 2023-09-27 20:53 UTC by Gab-D-G

2023-09-27 21:00 UTC, Gab-D-G commented
@gdevenyi please review contributing.md

2023-10-02 16:30 UTC, gdevenyi requested changes

2023-10-02 16:30 UTC, gdevenyi commented on docs/conf.py
> -release = '0.4.6'
This should be a seperate commit

2023-10-02 16:30 UTC, gdevenyi commented on docs/contributing.md
> +5. Commit and push your modifications to Github, and create a pull request from your forked repo to the original.
You need to mention making a branch

2023-10-02 16:30 UTC, gdevenyi commented on docs/requirements.txt
> -rabies==0.4.7
this should have a seperate commit with the version changes above

2023-10-02 16:30 UTC, gdevenyi commented on rabies/preprocess_pkg/utils.py
> -import numpy as np
This is another separate commit

2023-10-04 19:10 UTC, Gab-D-G commented
This branch is replaced by the documentation branch #331 , where the commit history is in line with @gdevenyi's feedback. The pull request will be closed.

2023-10-04 19:10 UTC, closed without merging